export type Sp100Constituent = {
  symbol: string;
  name: string;
  sector: string;
};

// S&P 100 / OEX working universe. Snapshot refreshed from S&P Global and
// iShares OEF public holdings pages on 2026-06-11.
export const SP100_CONSTITUENTS = [
  { symbol: "AAPL", name: "Apple", sector: "Information Technology" },
  { symbol: "ABBV", name: "AbbVie", sector: "Health Care" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Health Care" },
  { symbol: "ACN", name: "Accenture", sector: "Information Technology" },
  { symbol: "ADBE", name: "Adobe", sector: "Information Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Information Technology" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Information Technology" },
  { symbol: "AMGN", name: "Amgen", sector: "Health Care" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary" },
  { symbol: "AVGO", name: "Broadcom", sector: "Information Technology" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "BA", name: "Boeing", sector: "Industrials" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "BK", name: "BNY Mellon", sector: "Financials" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { symbol: "BLK", name: "BlackRock", sector: "Financials" },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Health Care" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Class B", sector: "Financials" },
  { symbol: "C", name: "Citigroup", sector: "Financials" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples" },
  { symbol: "CMCSA", name: "Comcast", sector: "Communication Services" },
  { symbol: "COF", name: "Capital One", sector: "Financials" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples" },
  { symbol: "CRM", name: "Salesforce", sector: "Information Technology" },
  { symbol: "CSCO", name: "Cisco", sector: "Information Technology" },
  { symbol: "CVS", name: "CVS Health", sector: "Health Care" },
  { symbol: "CVX", name: "Chevron", sector: "Energy" },
  { symbol: "DE", name: "Deere", sector: "Industrials" },
  { symbol: "DHR", name: "Danaher", sector: "Health Care" },
  { symbol: "DIS", name: "Walt Disney", sector: "Communication Services" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrials" },
  { symbol: "FDX", name: "FedEx", sector: "Industrials" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrials" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
  { symbol: "GEV", name: "GE Vernova", sector: "Industrials" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Health Care" },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { symbol: "GOOG", name: "Alphabet Class C", sector: "Communication Services" },
  { symbol: "GOOGL", name: "Alphabet Class A", sector: "Communication Services" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { symbol: "HON", name: "Honeywell", sector: "Industrials" },
  { symbol: "IBM", name: "IBM", sector: "Information Technology" },
  { symbol: "INTC", name: "Intel", sector: "Information Technology" },
  { symbol: "INTU", name: "Intuit", sector: "Information Technology" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health Care" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health Care" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer Staples" },
  { symbol: "LIN", name: "Linde", sector: "Materials" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Health Care" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer Discretionary" },
  { symbol: "LRCX", name: "Lam Research", sector: "Information Technology" },
  { symbol: "MA", name: "Mastercard", sector: "Financials" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { symbol: "MDT", name: "Medtronic", sector: "Health Care" },
  { symbol: "META", name: "Meta Platforms", sector: "Communication Services" },
  { symbol: "MMM", name: "3M", sector: "Industrials" },
  { symbol: "MO", name: "Altria", sector: "Consumer Staples" },
  { symbol: "MRK", name: "Merck", sector: "Health Care" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "MSFT", name: "Microsoft", sector: "Information Technology" },
  { symbol: "MU", name: "Micron Technology", sector: "Information Technology" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "NFLX", name: "Netflix", sector: "Communication Services" },
  { symbol: "NKE", name: "Nike", sector: "Consumer Discretionary" },
  { symbol: "NOW", name: "ServiceNow", sector: "Information Technology" },
  { symbol: "NVDA", name: "Nvidia", sector: "Information Technology" },
  { symbol: "ORCL", name: "Oracle", sector: "Information Technology" },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer Staples" },
  { symbol: "PFE", name: "Pfizer", sector: "Health Care" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { symbol: "PLTR", name: "Palantir Technologies", sector: "Information Technology" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Information Technology" },
  { symbol: "RTX", name: "RTX", sector: "Industrials" },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer Discretionary" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { symbol: "T", name: "AT&T", sector: "Communication Services" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Health Care" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { symbol: "TSLA", name: "Tesla", sector: "Consumer Discretionary" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Information Technology" },
  { symbol: "UBER", name: "Uber", sector: "Industrials" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Health Care" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrials" },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "V", name: "Visa", sector: "Financials" },
  { symbol: "VZ", name: "Verizon", sector: "Communication Services" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
] as const satisfies readonly Sp100Constituent[];

const SP100_BY_SYMBOL = new Map<string, Sp100Constituent>(
  SP100_CONSTITUENTS.map((constituent) => [constituent.symbol, constituent]),
);

export function normalizeSp100Symbol(input: string | undefined | null): string | null {
  if (!input) return null;
  const symbol = input.trim().replace(/^\$/, "").toUpperCase();
  return SP100_BY_SYMBOL.has(symbol) ? symbol : null;
}

export function getSp100Constituent(symbol: string): Sp100Constituent | null {
  return SP100_BY_SYMBOL.get(symbol.toUpperCase()) ?? null;
}
