import {beforeEach,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
const mock=vi.hoisted(()=>({auth:vi.fn(),admin:vi.fn(),rpc:vi.fn(),origin:vi.fn()}));
vi.mock('@/lib/chatAuth',()=>({requireChatUser:mock.auth}));
vi.mock('@/lib/chatAdmin',()=>({createChatAdminClient:mock.admin,requestOriginAllowed:mock.origin}));
import {GET,POST} from '@/app/api/chat/favorite/route';
import {favoriteHref,sameFavorite} from '@/lib/chatFavorite';
const id='12345678-1234-4234-8234-123456789abc';
const req=(body?:unknown)=>new NextRequest('https://example.test/api/chat/favorite?userId=forged',body===undefined?{}:{method:'POST',body:JSON.stringify(body),headers:{'content-type':'application/json'}});
beforeEach(()=>{vi.clearAllMocks();mock.auth.mockResolvedValue({ok:true,user:{id:'verified'}});mock.admin.mockReturnValue({rpc:mock.rpc});mock.origin.mockReturnValue(true);mock.rpc.mockResolvedValue({data:null});});
it('only reads the verified account',async()=>{expect(await(await GET(req())).json()).toEqual({favorite:null});expect(mock.rpc).toHaveBeenCalledWith('chat_favorite',{p_user_id:'verified',p_action:'get',p_room:null,p_conversation:null});});
it('origin-checks mutations before auth',async()=>{mock.origin.mockReturnValue(false);expect((await POST(req({favorite:null}))).status).toBe(403);expect(mock.auth).not.toHaveBeenCalled();});
it('requires authentication',async()=>{mock.auth.mockResolvedValue({ok:false,status:401,error:'unauthenticated'});expect((await GET(req())).status).toBe(401);expect((await POST(req({favorite:null}))).status).toBe(401);expect(mock.rpc).not.toHaveBeenCalled();});
it.each([{},null,{favorite:{}},{favorite:{kind:'room'}},{favorite:{kind:'room',room:'private'}},{favorite:{kind:'dm',conversationId:'bad'}}])('rejects malformed mutation %j',async body=>{expect((await POST(req(body))).status).toBe(400);expect(mock.rpc).not.toHaveBeenCalled();});
it('projects safe room identity and ignores caller supplied metadata',async()=>{mock.rpc.mockResolvedValue({data:{kind:'room',room:'social',email:'secret',label:'forged'}});const result=await POST(req({favorite:{kind:'room',room:'social',userId:'forged',label:'forged'}}));expect(await result.json()).toEqual({favorite:{kind:'room',room:'social',label:'SOCIAL'}});expect(result.headers.get('cache-control')).toBe('private, no-store');expect(mock.rpc).toHaveBeenCalledWith('chat_favorite',{p_user_id:'verified',p_action:'set',p_room:'social',p_conversation:null});});
it('sets only a conversation identifier and projects the server name',async()=>{mock.rpc.mockResolvedValue({data:{kind:'dm',conversationId:id,label:'Alice',email:'secret'}});expect(await(await POST(req({favorite:{kind:'dm',conversationId:id}}))).json()).toEqual({favorite:{kind:'dm',conversationId:id,label:'Alice'}});expect(mock.rpc).toHaveBeenCalledWith('chat_favorite',expect.objectContaining({p_conversation:id,p_room:null,p_action:'set'}));});
it('clears explicitly',async()=>{await POST(req({favorite:null}));expect(mock.rpc).toHaveBeenCalledWith('chat_favorite',expect.objectContaining({p_action:'clear',p_room:null,p_conversation:null}));});
it.each(['favorite_unavailable','member_required'])('fails closed on %s',async message=>{mock.rpc.mockResolvedValue({error:{message}});expect((await POST(req({favorite:{kind:'room',room:'main'}}))).status).toBe(403);});
it('hides server failures',async()=>{mock.rpc.mockRejectedValue(Error('secret'));const response=await GET(req());expect(response.status).toBe(503);expect(JSON.stringify(await response.json())).not.toContain('secret');});
it('builds existing room and DM navigation routes and compares targets',()=>{expect(favoriteHref({kind:'dm',conversationId:id},true)).toBe(`/chat?room=social&dm=${id}&popout=1`);expect(favoriteHref({kind:'room',room:'main'},false)).toBe('/chat?room=main');expect(sameFavorite({kind:'room',room:'main'},{kind:'room',room:'social'})).toBe(false);});
