import {beforeEach,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
import {POST} from '@/app/api/chat/route';
import {GET as cron} from '@/app/api/cron/chat-buddy/route';
import {processBuddyJobs} from '@/lib/chatBuddyJobs';
const mocks=vi.hoisted(()=>({auth:vi.fn(),member:vi.fn(),rpc:vi.fn(),from:vi.fn(),answer:vi.fn(),after:vi.fn()}));
vi.mock('next/server',async original=>({...await original<typeof import('next/server')>(),after:mocks.after}));
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({from:mocks.from,rpc:mocks.rpc})}));
vi.mock('@/lib/chatAdmin',async original=>({...await original<typeof import('@/lib/chatAdmin')>(),readPublicRoomState:async()=>({isOpen:true}),createChatAdminClient:()=>({from:mocks.from,rpc:mocks.rpc})}));
vi.mock('@/lib/chatAuth',()=>({requireChatUser:mocks.auth}));
vi.mock('@/lib/chatMembers',()=>({findChatMember:mocks.member,CHAT_UUID:/^[a-f\d-]{36}$/i}));
vi.mock('@/lib/chatBuddy',()=>({answerBuddy:mocks.answer}));
const id='00000000-0000-4000-8000-000000000001',clientId='00000000-0000-4000-8000-000000000002';
let prior:unknown=null,sendError:unknown=null,finishError:unknown=null,claimAvailable=true;
const message={id,body:'@Buddy explain this',room_slug:'main',attachment_ids:[],client_id:clientId,buddy_status:'pending'};
beforeEach(()=>{
 vi.clearAllMocks();prior=null;sendError=null;finishError=null;claimAvailable=true;
 const q={select:()=>q,eq:()=>q,gte:()=>q,lt:()=>q,order:()=>q,maybeSingle:async()=>({data:prior,error:null}),limit:async()=>({data:[],error:null})};mocks.from.mockReturnValue(q);
 mocks.rpc.mockImplementation(async(name:string)=>name==='send_chat_attachment_message'?{data:sendError?null:message,error:sendError}:name==='claim_chat_buddy_job'?{data:claimAvailable?{messageId:id,body:message.body,createdAt:'2026-09-18T12:00:00Z'}:null,error:null}:{data:true,error:finishError});
 mocks.auth.mockResolvedValue({ok:true,user:{id,role:'user'},access:{longboard:true,boardroom:true,shortscout:false,admin:false}});mocks.member.mockResolvedValue({id,display_name:'Member'});
 mocks.answer.mockResolvedValue({text:'Explanation'});
 vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL','https://example.supabase.co');vi.stubEnv('SUPABASE_SERVICE_ROLE_KEY','test-only');vi.stubEnv('CRON_SECRET','cron-test');
});
const request=()=>new NextRequest('https://example.test/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',room:'main',body:message.body,clientId})});
it('returns the persisted message while model work remains unresolved',async()=>{
 let resolveAnswer!:(value:{text:string})=>void;
 mocks.answer.mockReturnValue(new Promise(resolve=>{resolveAnswer=resolve;}));
 let background:Promise<void>|undefined;
 mocks.after.mockImplementation((callback:()=>Promise<void>)=>{background=callback();});
 const response=await Promise.race([POST(request()),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Send awaited model')),300))]);
 expect(response.status).toBe(200);expect((await response.json()).message).toEqual(message);
 expect(mocks.answer).toHaveBeenCalledOnce();expect(mocks.rpc).not.toHaveBeenCalledWith('finish_chat_buddy_job',expect.anything());
 resolveAnswer({text:'Explanation'});await background;
 expect(mocks.rpc).toHaveBeenCalledWith('finish_chat_buddy_job',expect.objectContaining({source:id,answer:'Explanation'}));
});
it('same-client retry returns persisted status without scheduling duplicate work',async()=>{prior=message;expect((await POST(request())).status).toBe(200);expect(mocks.after).not.toHaveBeenCalled();expect(mocks.rpc).not.toHaveBeenCalled();});
it('attachment failure does not schedule Buddy',async()=>{sendError={message:'attachment_not_ready'};expect((await POST(request())).status).toBe(409);expect(mocks.after).not.toHaveBeenCalled();});
it('worker passes bounded abort signal and caps stored reply at current DB limit',async()=>{mocks.answer.mockResolvedValue({text:'x'.repeat(900)});await processBuddyJobs({messageId:id,limit:1});expect(mocks.answer.mock.calls[0][2]).toBeInstanceOf(AbortSignal);expect(mocks.rpc.mock.calls.find(call=>call[0]==='finish_chat_buddy_job')![1].answer).toHaveLength(600);});
it('provider failure settles a safe retry without leaking provider details',async()=>{mocks.answer.mockRejectedValue(new Error('provider secret detail'));expect(await processBuddyJobs({messageId:id})).toEqual({processed:1});expect(mocks.rpc).toHaveBeenCalledWith('finish_chat_buddy_job',expect.objectContaining({answer:null}));});
it('worker propagates persistence failure so lease recovery handles it',async()=>{finishError={message:'database unavailable'};await expect(processBuddyJobs({messageId:id})).rejects.toThrow('buddy_finish_failed');});
it('cron refuses missing/wrong credentials and does not touch queue',async()=>{for(const authorization of ['', 'Bearer wrong'])expect((await cron(new NextRequest('https://example.test/api/cron/chat-buddy',{headers:{authorization}}))).status).toBe(401);expect(mocks.rpc).not.toHaveBeenCalled();});
it('cron can recover work using existing secret without a browser request',async()=>{claimAvailable=false;const response=await cron(new NextRequest('https://example.test/api/cron/chat-buddy',{headers:{authorization:'Bearer cron-test'}}));expect(response.status).toBe(200);expect(await response.json()).toEqual({processed:0});});
