import {afterEach,describe,expect,it,vi} from 'vitest';
import {AttachmentMetadataCache} from '../chatAttachmentMetadataCache';
const file=(id:string)=>({id,filename:id,mime_type:'image/png',byte_size:20});
afterEach(()=>vi.useRealTimers());
describe('account-owned attachment metadata batching',()=>{
 it('combines same-scope consumers, separates private conversations, caps batches at60',async()=>{vi.useFakeTimers();const calls:string[]=[];const fetcher=vi.fn(async(url:RequestInfo|URL)=>{calls.push(String(url));return Response.json({files:new URL(String(url),'http://test').searchParams.get('ids')!.split(',').map(file)});});const c=new AttachmentMetadataCache(fetcher as typeof fetch);const pending=[c.read({room:'main'},['a','b']),c.read({room:'main'},['b','c']),c.read({conversationId:'private'},Array.from({length:61},(_,i)=>String(i)))];await vi.advanceTimersByTimeAsync(20);const results=await Promise.all(pending);expect(calls).toHaveLength(3);expect(calls[0]).toContain('ids=a%2Cb%2Cc');expect(results[1].map(f=>f.id)).toEqual(['b','c']);expect(calls.every(url=>!url.includes('room=')||!url.includes('conversationId='))).toBe(true);c.dispose();});
 it('reuses short-lived entries but never crosses scope or provider instance',async()=>{vi.useFakeTimers();const fetcher=vi.fn(async()=>Response.json({files:[file('a')]}));const c=new AttachmentMetadataCache(fetcher as typeof fetch,()=>{},30);const first=c.read({room:'main'},['a']);await vi.advanceTimersByTimeAsync(20);await first;await c.read({room:'main'},['a']);expect(fetcher).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(31);const second=c.read({room:'main'},['a']);await vi.advanceTimersByTimeAsync(20);await second;expect(fetcher).toHaveBeenCalledTimes(2);const other=new AttachmentMetadataCache(fetcher as typeof fetch);const third=other.read({conversationId:'other'},['a']);await vi.advanceTimersByTimeAsync(20);await third;expect(fetcher).toHaveBeenCalledTimes(3);c.dispose();other.dispose();});
 it('notifies consumers and evicts scoped data when access becomes unavailable',async()=>{vi.useFakeTimers();let allowed=true;const unavailable=vi.fn();const fetcher=vi.fn(async()=>allowed?Response.json({files:[file('a')]}):Response.json({error:'forbidden'},{status:403}));const c=new AttachmentMetadataCache(fetcher as typeof fetch,unavailable);const first=c.read({conversationId:'dm'},['a']);await vi.advanceTimersByTimeAsync(20);await first;allowed=false;const denied=c.read({conversationId:'dm'},['missing']).catch(e=>e.message);await vi.advanceTimersByTimeAsync(20);expect(await denied).toContain('unavailable');expect(unavailable).toHaveBeenCalledWith('dm:dm');const again=c.read({conversationId:'dm'},['a']).catch(e=>e.message);await vi.advanceTimersByTimeAsync(20);await again;expect(fetcher).toHaveBeenCalledTimes(3);c.dispose();await expect(c.read({room:'main'},['a'])).rejects.toThrow('ended');});
 it('401 clears other scopes and rejects an older in-flight response without disabling retries',async()=>{vi.useFakeTimers();let release!:(response:Response)=>void;const fetcher=vi.fn(async(url:RequestInfo|URL)=>String(url).includes('conversationId=slow')?new Promise<Response>(resolve=>release=resolve):Response.json({error:'unauthorized'},{status:401}));const cleared=vi.fn(),c=new AttachmentMetadataCache(fetcher as typeof fetch,cleared);const slow=c.read({conversationId:'slow'},['a']).catch(e=>e.message);await vi.advanceTimersByTimeAsync(20);const denied=c.read({room:'main'},['b']).catch(e=>e.message);await vi.advanceTimersByTimeAsync(20);await denied;expect(cleared).toHaveBeenCalledWith('dm:slow');release(Response.json({files:[file('a')]}));expect(await slow).toContain('access changed');c.dispose();});

 it('invokes a browser-style fetch function without binding the cache as receiver',async()=>{vi.useFakeTimers();const fetcher=function(this:unknown){expect(this).toBeUndefined();return Promise.resolve(Response.json({files:[file('a')]}));};const c=new AttachmentMetadataCache(fetcher as typeof fetch);const result=c.read({room:'main'},['a']);await vi.advanceTimersByTimeAsync(20);expect((await result)[0].id).toBe('a');c.dispose();});

});
