import {describe,it,expect} from 'vitest';
import {pendingForScope,reconcilePendingMessages,mergeConfirmedMessages,type PendingChatMessage} from '@/lib/chatPendingMessages';
const pending=(clientId:string,scope='conversation:a',ownerId='alice'):PendingChatMessage=>({clientId,scope,ownerId,action:'send',targetId:'a',body:'Captured text',attachmentIds:['ready-file'],createdAt:'2026-09-18T12:00:00Z',status:'failed'});
describe('local message reconciliation',()=>{
 it('keeps failed retry payload and identity intact while excluding other scopes/accounts',()=>{const failed=pending('retry');const rows=[failed,pending('b','conversation:b'),pending('other','conversation:a','bob')];expect(pendingForScope(rows,'alice','conversation:a')).toEqual([failed]);expect(failed.attachmentIds).toEqual(['ready-file']);expect(failed.clientId).toBe('retry');});
 it('deduplicates a lost POST acknowledgement when polling returns its client UUID',()=>{const rows=[pending('lost'),pending('next')];expect(reconcilePendingMessages(rows,'alice','conversation:a',[{id:'server-id',client_id:'lost'}])).toEqual([rows[1]]);expect(rows[0].body).toBe('Captured text');});
 it('does not retire another owner or conversation even for the same client identifier',()=>{const rows=[pending('same'),pending('same','conversation:b'),pending('same','conversation:a','bob')];expect(reconcilePendingMessages(rows,'alice','conversation:a',[{id:'id',client_id:'same'}])).toEqual(rows.slice(1));});
 it('matches a canonical response ID when legacy reads omit client UUID',()=>{const row={...pending('ack'),status:'sent' as const,serverId:'server'};expect(reconcilePendingMessages([row],'alice','conversation:a',[{id:'server'}])).toEqual([]);});
 it('merges out-of-order acknowledgements without duplicating or rolling back edits/deletion',()=>{const first={id:'a',revision:0,body:'A'},second={id:'b',revision:0,body:'B'};const merged=mergeConfirmedMessages([second],[first,second]);expect(merged).toHaveLength(2);const deleted={...first,revision:2,body:'Message deleted'};expect(mergeConfirmedMessages([deleted],[first])).toEqual([deleted]);expect(mergeConfirmedMessages([first],[deleted])).toEqual([deleted]);});
});
