-- Durable cache for long-term momentum signals. The scanner and cron job use
-- service-role API routes only; no public RLS policies are defined.

create table if not exists long_term_momentum_signals (
  alert_key text primary key,
  et_date date not null,
  ticker text not null,
  name text,
  reference_type text,
  primary_exchange text not null default 'XNAS',
  signal_resolution text not null,
  signal_unix_seconds bigint not null,
  signal_time_et text not null,
  signal_rvol numeric not null,
  signal_price numeric not null,
  change_pct numeric not null,
  price_now numeric not null,
  day_volume numeric not null,
  dollar_volume numeric not null,
  breakout_mode text not null,
  breakout_level numeric not null,
  bars_scanned integer not null,
  source text not null default 'long-term-momentum-cache',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  raw_hit jsonb not null default '{}'::jsonb,
  constraint long_term_momentum_signals_ticker_chk
    check (ticker = upper(ticker) and ticker ~ '^[A-Z][A-Z0-9]{0,5}$'),
  constraint long_term_momentum_signals_exchange_chk
    check (primary_exchange = 'XNAS'),
  constraint long_term_momentum_signals_resolution_chk
    check (signal_resolution in ('1h', '4h')),
  constraint long_term_momentum_signals_breakout_chk
    check (breakout_mode in ('twoWeekHigh', 'monthToDateHigh')),
  constraint long_term_momentum_signals_prices_chk
    check (signal_price > 0 and price_now > 0),
  constraint long_term_momentum_signals_rvol_chk
    check (signal_rvol > 0),
  constraint long_term_momentum_signals_bars_chk
    check (bars_scanned > 0),
  constraint long_term_momentum_signals_unique_signal
    unique (ticker, signal_resolution, signal_unix_seconds)
);

create index if not exists long_term_momentum_signals_et_date_idx
  on long_term_momentum_signals (et_date desc, signal_resolution);

create index if not exists long_term_momentum_signals_ticker_idx
  on long_term_momentum_signals (ticker, signal_resolution, signal_unix_seconds desc);

create index if not exists long_term_momentum_signals_first_seen_idx
  on long_term_momentum_signals (first_seen_at desc);

alter table long_term_momentum_signals enable row level security;

revoke all on long_term_momentum_signals from anon;
revoke all on long_term_momentum_signals from authenticated;
grant select, insert, update, delete on long_term_momentum_signals to service_role;

create table if not exists long_term_momentum_scan_cursors (
  scanner_key text primary key,
  candidate_offset integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint long_term_momentum_scan_cursors_offset_chk
    check (candidate_offset >= 0)
);

alter table long_term_momentum_scan_cursors enable row level security;

revoke all on long_term_momentum_scan_cursors from anon;
revoke all on long_term_momentum_scan_cursors from authenticated;
grant select, insert, update, delete on long_term_momentum_scan_cursors to service_role;

create table if not exists long_term_momentum_scan_runs (
  id bigint generated by default as identity primary key,
  scanner_key text not null,
  status text not null,
  et_date date not null,
  candidate_offset integer not null,
  next_candidate_offset integer not null,
  snapshot_pool integer not null,
  candidate_limit integer not null,
  min_price numeric not null,
  min_move_pct numeric not null,
  max_price numeric,
  primary_exchanges text[] not null default array[]::text[],
  scanned integer not null default 0,
  signals integer not null default 0,
  error text,
  scans jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint long_term_momentum_scan_runs_status_chk
    check (status in ('ok', 'failed')),
  constraint long_term_momentum_scan_runs_offsets_chk
    check (candidate_offset >= 0 and next_candidate_offset >= 0),
  constraint long_term_momentum_scan_runs_limits_chk
    check (snapshot_pool > 0 and candidate_limit > 0),
  constraint long_term_momentum_scan_runs_min_price_chk
    check (min_price >= 1),
  constraint long_term_momentum_scan_runs_counts_chk
    check (scanned >= 0 and signals >= 0),
  constraint long_term_momentum_scan_runs_scans_array_chk
    check (jsonb_typeof(scans) = 'array')
);

create index if not exists long_term_momentum_scan_runs_created_idx
  on long_term_momentum_scan_runs (created_at desc);

create index if not exists long_term_momentum_scan_runs_date_idx
  on long_term_momentum_scan_runs (et_date desc, status);

alter table long_term_momentum_scan_runs enable row level security;

revoke all on long_term_momentum_scan_runs from anon;
revoke all on long_term_momentum_scan_runs from authenticated;
grant select, insert, update, delete on long_term_momentum_scan_runs to service_role;
grant usage, select on sequence long_term_momentum_scan_runs_id_seq to service_role;
